spring.application.name=keyboardbackend

# Conexión a PostgreSQL
spring.application.name=keyboardbackend
spring.datasource.url=jdbc:postgresql://localhost:5432/TecladosStore
spring.datasource.username=teclado_admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Configuración de Hibernate (validate = verifica que las clases coincidan con las tablas sin borrarlas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=8081